CREATE DATABASE wigi;
CREATE USER wigi_user IDENTIFIED BY 'w1g1u53r';
GRANT USAGE ON wigi.* to wigi_user IDENTIFIED BY 'w1g1u53r';
GRANT SELECT, INSERT, DELETE, UPDATE ON wigi.* to 'wigi_user' IDENTIFIED BY 'w1g1u53r' ;


CREATE TABLE users(
id INT UNSIGNED AUTO_INCREMENT NOT NULL,
facebook_id BIGINT UNSIGNED NOT NULL,
access_token text NOT NULL,
PRIMARY KEY(id),
INDEX(facebook_id)
) ENGINE=MYISAM DEFAULT CHARACTER SET UTF8;;

CREATE TABLE wigi_tokens(
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
user_id INT UNSIGNED NOT NULL REFERENCES users (id),
wigi_token VARCHAR(32) NOT NULL,
PRIMARY KEY(id),
INDEX(user_id)
) ENGINE=INNODB DEFAULT CHARACTER SET UTF8;;

CREATE TABLE wigi_items(
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
user_id INT UNSIGNED NOT NULL REFERENCES users (id),
image_location text NOT NULL,
status ENUM('want_it','get_it'),
initial_comment text,
PRIMARY KEY(id),
INDEX(user_id)
) ENGINE=INNODB DEFAULT CHARACTER SET UTF8;;


CREATE TABLE wigi_item_tags(
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
item_id INT UNSIGNED NOT NULL REFERENCES wigi_items (id),
tag text ,
PRIMARY KEY(id),
INDEX(item_id)
) ENGINE=INNODB DEFAULT CHARACTER SET UTF8;;

CREATE TABLE wigi_item_comments(
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
item_id INT UNSIGNED NOT NULL REFERENCES wigi_items (id),
comment text ,
PRIMARY KEY(id),
INDEX(item_id)
) ENGINE=INNODB DEFAULT CHARACTER SET UTF8;;

